### ISSUE TITLE
Update unknown speaker names on Hacktoberfest part 1

### ISSUE THREAD

**Issue by emmabostian** [ladybug-podcast/ladybugpodcast#50]
Some of the speaker names have "Unknown speaker" as their label and should be updated to reflect either Peter Frank or Jess Lee.

**Comment by objNameGit** [comment]
I'm sorry, I did not understand. Where can I see a list of speaker names with labels?

**Comment by emmabostian** [comment]
The episode hasn't been released yet :) It will come out on Monday

**Comment by objNameGit** [comment]
ohh. ok)

**Comment by pachicodes** [comment]
Can I help with this issue?

**Comment by emmabostian** [comment]
This was merged in as a fix already! HOWEVER @pachicodes if you'd like you can open another PR to make each name bold with ** :)

**Comment by pachicodes** [comment]
I can do that @emmawedekind !
Where can I ind the file?
thanks
