### ISSUE TITLE
Add a link to the GitHub repository on the website

### ISSUE THREAD

**Issue by juliette-derancourt** [ladybug-podcast/ladybugpodcast#57]
Hi!

First of all, congrats on the podcast, it's been really great to listen to! 👏

I noticed that there is no link towards this repo on https://ladybug.dev (or am I blind?), and I think it could be interesting to have it for people who want to contribute. I know it's not difficult to find and you tweeted it a bunch of times, but a direct link would be much more convenient.

Maybe a GitHub icon could be added:
- At the top right next to the Twitter one? (Even though this area feels more dedicated to the podcast itself)
- At the bottom next to the Netlify badge?

I'd also add a link to go back from the repo to the website, maybe in the readme or in the repo's description (I know there is already a link on the logo, but tbh I didn't know it was there until I looked at the raw markdown file... 😅 So maybe an explicit link wouldn't hurt, on "Our podcast website" for instance).

If any of these thoughts sounds like a good idea to you, I'd be happy to do it 😉

**Comment by lkreimann** [comment]
Hey Juliette, that idea sounds great! I would suggest adding that link next to the Twitter logo too, but that's just my opinion. 

Regarding the link from the repo back to the homepage: I would like that link in the description :+1: 

Just leaving my thoughts here!

**Comment by designMoreWeb** [comment]
This change has been implemented and merged 😄
